const httpErrors = require("http-errors");
const { User } = require("../models");
const createHttpError = require("http-errors");

module.exports.createUser = async (req, res, next) => {
  try {
    const { body } = req;

    const user = await User.create(body);

    res.status(201).send({ data: user });
  } catch (error) {
    next(error);
  }
};

module.exports.getAllUsers = async (req, res, next) => {
  try {
    const users = await User.find();

    res.send({ data: users });
  } catch (error) {
    next(error);
  }
};

module.exports.getUser = async (req, res, next) => {
  try {
    const {
      params: { userId },
    } = req;

    const foundUser = await User.findById(userId);

    if (!foundUser) {
      return next(createHttpError(404, "User not found"));
    }

    res.send({ data: foundUser });
  } catch (error) {
    next(error);
  }
};

module.exports.updateUser = async (req, res, next) => {
  try {
    const {
      params: { userId },
      body,
    } = req;

    const updateUser = await User.findByIdAndUpdate(userId, body, {
      new: true,
    });

    res.send({ data: updateUser });
  } catch (error) {
    next(error);
  }
};

module.exports.deleteUser = async (req, res, next) => {
  try {
    const {
      params: { userId },
    } = req;

    const user = await User.findByIdAndDelete(userId);

    res.send({ data: user });
  } catch (error) {
    next(error);
  }
};
